changelog:
  categories:
    - title: "🚀 New Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🧰 Maintenance"
      labels:
        - "documentation"
        - "dependencies"