[package]
name = "runpkg"
version = "0.1.0"
edition = "2024"
authors = ["zeMinng"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive", "env"] }
crossterm = "0.27"
ratatui = "0.26"
tokio = { version = "1.36", features = ["full"] }
colored = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"