[package]
name = "runpkg"
description = "runpkg — Interactive package.json manager for your terminal."
version = "0.0.1"
edition = "2024"
authors = ["zeMinng"]
repository = "https://github.com/zeMinng/runpkg"
homepage = "https://github.com/zeMinng/runpkg"

[package.metadata.wix]
upgrade-guid = "6A2C9775-D39E-4452-BE48-A94D93D7C351"
path-guid = "9422AC1D-C78E-4099-A190-FBDE45381D86"
license = false
eula = false

[dependencies]
# CLI 参数解析
clap = { version = "4.4", features = ["derive"] }
# TUI 与终端控制
ratatui = "0.26"
crossterm = "0.27"
# 数据序列化与文件解析
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# 错误处理
anyhow = "1.0"

tokio = { version = "1.36", features = ["full"] }
colored = "2.1"
indexmap = { version = "2.0", features = ["serde"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
